apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1035879662-deployment
  labels:
    app: ccac-1035879662
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccac-1035879662
  template:
    metadata:
      labels:
        app: ccac-1035879662
    spec:
      containers:
      - name: mi-contenedor
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/c1035879662:latest
        ports:
        - containerPort: 5000
